project:
  type: website
  output-dir: docs

website:
  title: "Learning Azure Authentication and Authorization"
  page-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - topics.qmd
  sidebar:
    - title: "Home"
      style: "docked"
      background: light
      contents:
        - text: "---"
        - topics.qmd        
        - text: "---"
        - topics/follow-the-zero-trust-guidelines.qmd
        - text: "---"
        - topics/what-is-identity-and-access-management.qmd
        - text: "---"
        - topics/when-to-use-azure-active-directory.qmd
        - text: "---"
        - topics/when-to-use-azure-active-directory-business-to-consumer.qmd
        - text: "---"
        - topics/when-to-use-azure-active-directory-business-to-business.qmd
        - text: "---"
        - topics/compare-azure-ad-business-to-consumer-to-business-to-business.qmd
        - text: "---"
        - topics/when-to-use-conditional-access.qmd
        - text: "---"
        - topics/when-to-use-identity-protection.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
