project:
  type: website
  output-dir: docs

website:
  title: "Learning Azure Authentication and Authorization"
  page-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - topics.qmd
  sidebar:
    - title: "Home"
      style: "docked"
      background: light
      contents:
        - text: "---"
        - topics.qmd        
        - text: "---"
        - topics/follow-the-zero-trust-guidelines.qmd
        - text: "---"
        - topics/what-is-identity-and-access-management.qmd        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
